### ISSUE TITLE
Spyder 5 compatibility?

### ISSUE THREAD

**Issue by catanzaromj** [spyder-ide/spyder-memory-profiler#34]
After installing spyder-memory-profiler, nothing about the `Run` menu changes indicating that the plugin is loaded. Entering debug mode, I see the following error

```
[DEBUG] [spyder.otherplugins] -> plugin: 'spyder_memory_profiler' load failed with `cannot import name 'get_icon' from 'spyder.utils.qthelpers' (/home/USER/miniconda3/envs/spyder-env/lib/
python3.9/site-packages/spyder/utils/qthelpers.py)`
```
Looking at git diffs, it seems that `spyder/utils/qthelpers.py` has changed since spyder 4.x. This is the only other error I found in the debug log, but that doesn't mean the rest of the code is compatible with spyder 5 either. 

I'm happy to help with implementing this change or attempting to update the package in general, but I don't know anything about spyder plug-ins. If anyone could point me in the right direction of where to start, I'd attempt a fix. Thanks.

**Comment by jitseniesen** [comment]
You are correct to say that the plugin is not compatible with Spyder 5. You can look at PR spyder-ide/spyder-line-profiler#56, which is what made the spyder-line-profiler plugin compatible with Spyder 5. The code is pretty similar so that should give you a good idea of what is needed (and how much work it is). I would be very happy to merge a PR along these lines and answer any questions you have. Let me know if you want to give it a go.

**Comment by catanzaromj** [comment]
Thanks for the quick reply. After looking over the link you sent and the [site on spyder plugin development](https://docs.spyder-ide.org/current/workshops/plugin-development.html), I think it's potentially a lot of work but totally plausible. One thing I worry about is I read that Spyder 6 may be coming out at the end of this year/early next year. If this is the case, will the plugin just break again? Is it better to wait until Spyder 6 comes out and then update the plugin? I also wonder what updating this plugin means in the context of "Support and improve third-party and native Spyder plugins" as mentioned on the [Themes for 2022 page](https://github.com/spyder-ide/spyder/wiki/Roadmap).

**Comment by ccordoba12** [comment]
> If this is the case, will the plugin just break again?

Perhaps, but it'll be much easier to update because we won't make as much breaking changes as we did in Spyder 5. The thing is we created a new API for plugins in that version, and that's why it's been really slow to update external plugins to it.

> Is it better to wait until Spyder 6 comes out and then update the plugin?

No, the update should be much simpler in that case, as I said.

Let us know if you have free time to invest on this. If not, I'll try to do it in the next couple of months.

**Comment by catanzaromj** [comment]
Thanks for the reply. I do have some time so I will try to get going on it.

**Comment by catanzaromj** [comment]
@jitseniesen @ccordoba12 Sorry I have been swamped with work. I don't think I'll have time to do this in the near future.

**Comment by jitseniesen** [comment]
No worries, thanks for letting us know. I know the feeling, hope things will get better soon.

**Comment by jitseniesen** [comment]
We decided to officially stop maintaining the plugin, so I am closing all issues.
